/* Generated By:JavaCC: Do not edit this line. PigScriptParserConstants.java */
package org.apache.pig.tools.pigscript.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PigScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CAT = 6;
  /** RegularExpression Id. */
  int FS = 7;
  /** RegularExpression Id. */
  int SH = 8;
  /** RegularExpression Id. */
  int CD = 9;
  /** RegularExpression Id. */
  int COPY = 10;
  /** RegularExpression Id. */
  int COPYFROMLOCAL = 11;
  /** RegularExpression Id. */
  int COPYTOLOCAL = 12;
  /** RegularExpression Id. */
  int DUMP = 13;
  /** RegularExpression Id. */
  int DESCRIBE = 14;
  /** RegularExpression Id. */
  int ALIASES = 15;
  /** RegularExpression Id. */
  int EXPLAIN = 16;
  /** RegularExpression Id. */
  int HELP = 17;
  /** RegularExpression Id. */
  int KILL = 18;
  /** RegularExpression Id. */
  int LS = 19;
  /** RegularExpression Id. */
  int MOVE = 20;
  /** RegularExpression Id. */
  int MKDIR = 21;
  /** RegularExpression Id. */
  int PWD = 22;
  /** RegularExpression Id. */
  int QUIT = 23;
  /** RegularExpression Id. */
  int REGISTER = 24;
  /** RegularExpression Id. */
  int USING = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int REMOVE = 27;
  /** RegularExpression Id. */
  int REMOVEFORCE = 28;
  /** RegularExpression Id. */
  int SET = 29;
  /** RegularExpression Id. */
  int ILLUSTRATE = 30;
  /** RegularExpression Id. */
  int RUN = 31;
  /** RegularExpression Id. */
  int EXEC = 32;
  /** RegularExpression Id. */
  int PARAM = 33;
  /** RegularExpression Id. */
  int PARAM_FILE = 34;
  /** RegularExpression Id. */
  int SCRIPT = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int OUT = 37;
  /** RegularExpression Id. */
  int BRIEF = 38;
  /** RegularExpression Id. */
  int SCRIPT_DONE = 39;
  /** RegularExpression Id. */
  int PIG = 102;
  /** RegularExpression Id. */
  int EOL = 103;
  /** RegularExpression Id. */
  int QUOTE = 104;
  /** RegularExpression Id. */
  int SEMICOLON = 105;
  /** RegularExpression Id. */
  int LETTER = 106;
  /** RegularExpression Id. */
  int DIGIT = 107;
  /** RegularExpression Id. */
  int SPECIALCHAR = 108;
  /** RegularExpression Id. */
  int FSSPECIALCHAR = 109;
  /** RegularExpression Id. */
  int FLOAT = 110;
  /** RegularExpression Id. */
  int INTEGER = 111;
  /** RegularExpression Id. */
  int NUMBER = 112;
  /** RegularExpression Id. */
  int IDENTIFIER = 113;
  /** RegularExpression Id. */
  int PATH = 114;
  /** RegularExpression Id. */
  int QUOTEDSTRING = 115;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PIG_START = 1;
  /** Lexical state. */
  int SINGLE_LINE_COMMENT = 2;
  /** Lexical state. */
  int MULTI_LINE_COMMENT = 3;
  /** Lexical state. */
  int IN_STRING = 4;
  /** Lexical state. */
  int IN_COMMAND = 5;
  /** Lexical state. */
  int GENERATE = 6;
  /** Lexical state. */
  int SCHEMA_DEFINITION = 7;
  /** Lexical state. */
  int BAG_CONSTANT = 8;
  /** Lexical state. */
  int IN_BLOCK = 9;
  /** Lexical state. */
  int IN_DOUBLE_QUOTED_STRING = 10;
  /** Lexical state. */
  int PIG_END = 11;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"cat\"",
    "\"fs\"",
    "\"sh\"",
    "\"cd\"",
    "\"cp\"",
    "\"copyFromLocal\"",
    "\"copyToLocal\"",
    "\"dump\"",
    "\"describe\"",
    "\"aliases\"",
    "\"explain\"",
    "\"help\"",
    "\"kill\"",
    "\"ls\"",
    "\"mv\"",
    "\"mkdir\"",
    "\"pwd\"",
    "\"quit\"",
    "\"register\"",
    "\"using\"",
    "\"as\"",
    "\"rm\"",
    "\"rmf\"",
    "\"set\"",
    "\"illustrate\"",
    "\"run\"",
    "\"exec\"",
    "\"-param\"",
    "\"-param_file\"",
    "\"-script\"",
    "\"-dot\"",
    "\"-out\"",
    "\"-brief\"",
    "\"scriptDone\"",
    "\"split\"",
    "\"define\"",
    "\"store\"",
    "\"import\"",
    "<token of kind 44>",
    "<token of kind 45>",
    "<token of kind 46>",
    "\"\\\'\"",
    "\"`\"",
    "<token of kind 49>",
    "<token of kind 50>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 56>",
    "<token of kind 57>",
    "<token of kind 58>",
    "<token of kind 59>",
    "\"*/\"",
    "<token of kind 61>",
    "<token of kind 62>",
    "\"\\\\\\\'\"",
    "\"\\\'\"",
    "<token of kind 65>",
    "<token of kind 66>",
    "\"\\\\`\"",
    "\"`\"",
    "<token of kind 69>",
    "<token of kind 70>",
    "\"{\"",
    "<token of kind 72>",
    "\";\"",
    "<token of kind 74>",
    "<token of kind 75>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 80>",
    "<token of kind 81>",
    "<token of kind 82>",
    "\"{\"",
    "\"}\"",
    "<token of kind 85>",
    "<token of kind 86>",
    "\"\\\"\"",
    "<token of kind 88>",
    "<token of kind 89>",
    "\"{\"",
    "<token of kind 91>",
    "\"\\\'\"",
    "\"`\"",
    "\"--\"",
    "\"/*\"",
    "<token of kind 96>",
    "<token of kind 97>",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<token of kind 100>",
    "<token of kind 101>",
    "\"\"",
    "<EOL>",
    "\"\\\'\"",
    "\";\"",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIALCHAR>",
    "<FSSPECIALCHAR>",
    "<FLOAT>",
    "<INTEGER>",
    "<NUMBER>",
    "<IDENTIFIER>",
    "<PATH>",
    "<QUOTEDSTRING>",
  };

}
